# Generated by Django 5.2 on 2025-04-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privatemessage',
            options={},
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
