# Generated by Django 5.2 on 2025-04-25 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_privatemessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privatemessage',
            options={'ordering': ['timestamp']},
        ),
    ]
